# exceptions.bill
# for exceptions sample

fun noval main(argv):
{
    fun noval mistake():
     {
        try:
        {
            doThis();
        }
        catch(RuntimeError e):
        {
            throw(RuntimeError(e));
        }
    }

    try:
    {
        mistake();
    }
    catch(RuntimeError e)
    {
        writeln(e);
        exit(1);
    }

    # Results are in a generic message, as none is defined here, and a backtrace.
}

